[tool.poetry]
name = "misis-chatbots"
version = "0.1.0"
description = ""
authors = ["Daniil Zhdanov <zhdanov.daniil7@wb.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.*"
rasa = "^3.6.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
